name: Sync to Hugging Face

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Create HF deployment directory
        run: |
          mkdir hf_push
          cp -a --ignore=hf_push . hf_push/
          
      - name: Verify LFS files
        run: |
          cd hf_push
          git lfs ls-files

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf_push

          git init

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Deploy backend from GitHub"

          git remote add hf https://mockingjay-7:$HF_TOKEN@huggingface.co/spaces/mockingjay-7/HydroSense

          git push --force hf HEAD:main

      - name: Cleanup
        if: always()
        run: |
          rm -rf hf_push