name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create clean deployment commit
        run: |
          git checkout --orphan hf-deploy

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Deploy $(date)"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://mockingjay-7:$HF_TOKEN@huggingface.co/spaces/mockingjay-7/HydroSense
          git push hf hf-deploy:main --force